### ISSUE TITLE
Syntax highlighting not correct between two forward slashes

### ISSUE THREAD

**Issue by GarmOfGnipahellir** [atom/language-coffee-script#112]
Reproduced in safe mode below.
![csdivisionhighlighting](https://cloud.githubusercontent.com/assets/24740578/22631566/f2eab8bc-ec0f-11e6-97aa-80b7e936dd74.PNG)
I'm guessing its a problem with regex interpretation.

**Comment by 50Wliu** [comment]
Yep, and it's pretty impossible to fix.

**Comment by julians** [comment]
Is this caused by the same bug?

![bildschirmfoto 2017-02-07 um 09 19 05](https://cloud.githubusercontent.com/assets/38328/22683079/892ce596-ed16-11e6-9989-42177d93887f.png)

**Comment by 50Wliu** [comment]
Looks like it.

**Comment by ezekg** [comment]
This is a recent bug. I manually reverted back to v0.47.3 using `apm`.

**Comment by 1j01** [comment]
@50Wliu Care to elaborate on "pretty impossible to fix"? (CoffeeScript parses CoffeeScript, after all.)

Also, in @julians example and here:
![atom coffeescript](https://cloud.githubusercontent.com/assets/3630663/22758031/ea93d790-ee1a-11e6-85fb-22cbcf26e7ce.gif)
It's deciding there's a regex based on that second slash, but also ignoring the slash because it's inside some parentheses:
![atom coffeescript](https://cloud.githubusercontent.com/assets/3630663/22758162/7bbd5912-ee1b-11e6-8eaa-83ea06c9f457.png)
And non-heregexes aren't even supposed to span lines.

**Comment by 50Wliu** [comment]
Basically, using only regexes, it is impossible to fully differentiate between division and regex.  We can have it either be more prone to matching something as regex than division or vice versa, but we'll never be able to perfectly figure out which one to use without knowing more context.

In this case, I think I'm going to revert the commit that caused this, which was allowing spaces in regex (which is totally fine...but it seems like this has the larger side effect of breaking multiple division signs).

Also, you're totally right about normal regexes not being able to span multiple lines.  I'll include that as part of my fix.
